### ISSUE TITLE
Installation errors for cloned repo

### ISSUE THREAD

**Issue by drewpchannel** [open-austin/budgetparty#110] opened 2017-05-11 01:31 UTC
after forking, cloning and npm installing the page would fail to load index.js.

to fix this we did npm i -S accounting
then npm i react-intl

this fixed the issue

**Comment by VictoriaODell** [comment] 2017-05-11 01:52
lol ya'll made these 1 minute apart. 

Dupe of issue #109

**Closed by VictoriaODell** 2017-05-11 01:52 UTC

**Comment by mateoclarke** [comment] 2017-05-11 05:51
I suck. @drewpchannel, you rock
